### ISSUE TITLE
Is there a way to make arrangments based on a grouping by variable

### ISSUE THREAD

**Issue by mattfidler** [randy3k/arrangements#1]
Hi,

This package looks excellent.  I was wondering if there was a built-in way to make arrangments of some time-varying item by some grouping characteristic like ID;  It seems to arrange only one item.

**Comment by randy3k** [comment]
I am not entirely sure if I understand it. Could you show an example?

**Comment by mattfidler** [comment]
Sure

```
> dat
ID Cov 
1 0.1
1 0.2
1 0.3
2 2.1
2 2.2
2 2.3
3 3.3
3 3.4
3 3.5
```

So to select with replacement (assuming all IDs are of the same length) something like:

```
combinations(9, data.frame=dat, 6, replace = TRUE)
```
would produce combinations of the above dataset by ID.

Thats OK, I think I will have to do something a bit more fancy in case the IDs have different number of observations for a covariate.
