### ISSUE TITLE
Error when the elements are numbers ??

### ISSUE THREAD

**Issue by juanpide** [randy3k/arrangements#2]
I'm using arrangements v1.1.5 with R v3.5.3 in Windows 10.
And I think I have found a strange error or I'm doing something wrong.

This is working

```
myDF <- data.frame(A=c("a","b","c"), B=c(2000,2000,2002))
tapply(myDF$A,myDF$B, permutations)

$`2000`
     [,1] [,2]
[1,] a    b   
[2,] b    a   
Levels: a b c

$`2002`
     [,1]
[1,] c   
Levels: a b c
```

But this isn't working:
```
myDF <- data.frame(A=c(200,200,200), B=c(0,0,2))
tapply(myDF$A,myDF$B, permutations)

Error in FUN(X[[i]], ...) : too many results
```

What am I doing wrong?   
I just want to get generate the permutations of the elements of A defined by the group B.   
The result should be like the former example but with numbers.

**Comment by randy3k** [comment]
It is because the first argument of `permutations` could be either a vector or an integer.

```r
r$> permutations(c(3, 1))
     [,1] [,2]
[1,]    3    1
[2,]    1    3

r$> permutations(3)
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    1    3    2
[3,]    2    1    3
[4,]    2    3    1
[5,]    3    1    2
[6,]    3    2    1
```

`permutations(3)` is not simply the permutations of the single vector which contains only the element 3.
For that, you need `permutations(v = 3)`


Okay, go back to your question

```
myDF <- data.frame(A=c(200,200,200), B=c(0,0,2))
tapply(myDF$A, myDF$B, function(v) permutations(v = v))
```
